import React, { useState } from 'react';
import {
  Search,
  Command,
  Sun,
  Moon,
  Bell,
  Sparkles,
  CheckCircle,
  AlertCircle,
  Clock,
} from 'lucide-react';
import { useTheme } from '../../context/ThemeContext';
import { useAuth } from '../../context/AuthContext';
import { Badge } from '../ui/Badge';

interface NavbarProps {
  onOpenCommandPalette: () => void;
  onOpenAiAssistant: () => void;
  activeTabTitle: string;
}

export const Navbar: React.FC<NavbarProps> = ({
  onOpenCommandPalette,
  onOpenAiAssistant,
  activeTabTitle,
}) => {
  const { theme, toggleTheme } = useTheme();
  const { user } = useAuth();
  const [showNotifications, setShowNotifications] = useState(false);

  const notifications = [
    { id: 1, title: 'Low Stock Alert', desc: '8-Port Ethernet Switch (12 units remaining)', time: '10m ago', icon: AlertCircle, color: 'text-amber-400' },
    { id: 2, title: 'New Sales Challan', desc: '#CH-2026-00903 generated by Rajesh', time: '1h ago', icon: CheckCircle, color: 'text-emerald-400' },
    { id: 3, title: 'AI Recommendation', desc: 'Restock TS-Q200 to prevent $12k revenue loss', time: '3h ago', icon: Sparkles, color: 'text-cyan-400' },
  ];

  return (
    <header className="no-print sticky top-0 z-20 h-16 glass-panel border-b border-white/10 px-6 flex items-center justify-between backdrop-blur-xl">
      {/* Active View Header */}
      <div className="flex items-center gap-3">
        <h1 className="text-lg font-bold text-white tracking-tight">{activeTabTitle}</h1>
        <Badge variant="purple" className="hidden sm:inline-flex text-[10px]">
          Live Workspace
        </Badge>
      </div>

      {/* Global Action Bar */}
      <div className="flex items-center gap-3">
        {/* Command Palette Trigger */}
        <button
          onClick={onOpenCommandPalette}
          className="hidden md:flex items-center gap-3 px-3.5 py-1.5 rounded-xl glass-input text-xs text-slate-400 hover:text-white transition-all shadow-sm group"
        >
          <Search className="w-3.5 h-3.5 text-slate-400 group-hover:text-[#00D4FF] transition-colors" />
          <span>Search or type command...</span>
          <kbd className="inline-flex items-center gap-0.5 px-2 py-0.5 rounded bg-white/10 text-[10px] text-slate-300 border border-white/10 font-mono">
            <Command className="w-2.5 h-2.5" /> K
          </kbd>
        </button>

        {/* AI Assistant Quick Trigger Button */}
        <button
          onClick={onOpenAiAssistant}
          className="flex items-center gap-2 px-3 py-1.5 rounded-xl bg-gradient-to-r from-[#5B5FFF]/20 via-[#7C3AED]/20 to-[#00D4FF]/20 border border-[#5B5FFF]/40 text-xs font-semibold text-white hover:border-[#00D4FF] hover:shadow-glow-accent transition-all"
        >
          <Sparkles className="w-3.5 h-3.5 text-[#00D4FF] animate-pulse" />
          <span className="hidden sm:inline">AI Copilot</span>
        </button>

        {/* Theme Switcher */}
        <button
          onClick={toggleTheme}
          className="p-2 rounded-xl glass-panel text-slate-300 hover:text-white hover:bg-white/10 transition-colors"
          title={`Switch to ${theme === 'dark' ? 'Light' : 'Dark'} Mode`}
        >
          {theme === 'dark' ? <Sun className="w-4 h-4 text-amber-400" /> : <Moon className="w-4 h-4 text-indigo-600" />}
        </button>

        {/* Notifications Dropdown */}
        <div className="relative">
          <button
            onClick={() => setShowNotifications(!showNotifications)}
            className="relative p-2 rounded-xl glass-panel text-slate-300 hover:text-white hover:bg-white/10 transition-colors"
          >
            <Bell className="w-4 h-4" />
            <span className="absolute top-1 right-1 w-2 h-2 rounded-full bg-[#00D4FF] animate-ping" />
            <span className="absolute top-1 right-1 w-2 h-2 rounded-full bg-[#00D4FF]" />
          </button>

          {showNotifications && (
            <div className="absolute right-0 mt-3 w-80 glass-panel rounded-2xl p-4 border border-white/20 shadow-2xl z-50 bg-[#0B1020]/95 backdrop-blur-2xl">
              <div className="flex items-center justify-between border-b border-white/10 pb-3 mb-3">
                <h4 className="text-xs font-bold text-white uppercase tracking-wider">Realtime Alerts</h4>
                <span className="text-[10px] text-[#00D4FF] font-semibold">3 Unread</span>
              </div>
              <div className="space-y-3">
                {notifications.map((n) => {
                  const Icon = n.icon;
                  return (
                    <div key={n.id} className="flex items-start gap-3 p-2 rounded-xl hover:bg-white/5 transition-colors">
                      <Icon className={`w-4 h-4 shrink-0 mt-0.5 ${n.color}`} />
                      <div className="flex-1 min-w-0">
                        <p className="text-xs font-semibold text-white leading-tight">{n.title}</p>
                        <p className="text-[11px] text-slate-400 mt-0.5 leading-snug">{n.desc}</p>
                        <span className="text-[9px] text-slate-500 flex items-center gap-1 mt-1">
                          <Clock className="w-2.5 h-2.5" /> {n.time}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
        </div>
      </div>
    </header>
  );
};